### ISSUE TITLE
Aide 

### ISSUE THREAD

**Issue by tardistef** [wikijm/jarvis-freeboxplayer#10]
Bonjour, 
Je vient d'installer Jarvis, et le plugin freebox, j'ai rentré le code de la télécommande de la free, j'ai laissé hd1 par défaut, mais je ne voit pas comment on appel les commandes, de la free, 
Merci de votre aide.

**Comment by wikijm** [comment]
Bonsoir @tardistef,

Les commandes sont définies dans le fichier https://github.com/wikijm/jarvis-freeboxplayer/blob/master/fr/commands

Il faut ensuite suivre ce qui est décrit ici : http://openjarvis.com/content/plugins

**Comment by tardistef** [comment]
Bonjour,
Merci j'ai vu mon erreur, c'est la commande vocal qui merde, pas les commande plugin.
J'ai fait un test en commande console et les commande fonctionnent.
C'est ma reconnaissance vocal qui veut pas prendre mes commandes.
Je sais pas pourquoi d'ailleurs.....

**Comment by wikijm** [comment]
Merci pour le retour 😃 

Je vous invite à créer une issue sur le repo d'OpenJarvis si jamais vous aviez d'autres problèmes au global.

Bon week-end,
@wikijm
