### ISSUE TITLE
Modification des commandes?

### ISSUE THREAD

**Issue by LordDarkneo** [wikijm/jarvis-freeboxplayer#11]
Hello!!

J'ai voulu modifier les commandes du plugins... Ce qui a eu pour effet de ne plus le faire fonctionner du tout! en gros, quand je veux afficher NRJ12, il me met un espace en NRJ et 12... Donc la commande n'est pas reconnue....

un petit extrait:
Jarvis: Je n'ai pas compris: affiche NRJ 12
DEBUG: using cache /dev/shm/je_nai_pas_compris_affiche_nrj_12.mp3

JE pense qu'il faut rajouter des "*" entre chaque mot (car j'ai le même problème sur M6, France 3, etc...)

Et quand j'ai voulu faire la modif moi même sur le fichier de command... ben plus rien ne fonctionnait (modif faite via nano).

du coup:
- Tu peux faire les mises à jour toi?
- Vu que c'est quand même pratique, comment on peut modifier les commandes du plugin sans tout péter? (Je pense y adjoindre pas mal de fonctionnalités côté radio, navigation sur le nas, etc...)

**Comment by wikijm** [comment]
Bonsoir @LordDarkneo,

Je n'ai pas réussi à recréer ton problème.
En revanche, tu peux modifier le fichier commande de cette façon :

Avant :
```bash
*AFFICH*NRJ12*|*AFFICH*NRJ*DOUZ*==say "N R J 12" && jv_curl "${freeboxplayer_url}1" && jv_curl "${freeboxplayer_url}2">/dev/null
```
Après :
```bash
*AFFICH*NRJ12*|*AFFICH*NRJ*12*|*AFFICH*NRJ*DOUZ*==say "N R J 12" && jv_curl "${freeboxplayer_url}1" && jv_curl "${freeboxplayer_url}2">/dev/null
```

**Comment by LordDarkneo** [comment]
Hello @wikjim. C'est la modif que j'avais faite maos le plugin ne fonctionnait plus après... je retente ce soir ;)

**Comment by wikijm** [comment]
Bonjour @LordDarkneo,

As-tu eu le temps de retester ?

**Comment by LordDarkneo** [comment]
Hello !
Oui désolé j'ai oublié de passer donner des news. Oui c'est nickel j'ai rajouté des * entre chaque mot/numéro (france*2, nrj*12,...). Et le bug je pense que c'est parce que j'avais modifié les commandes dans plugin\installed et pas dans plugin\enabled (ce deuxième etant je pense celui qui est utilisé par Jarvis)
Merci!

**Comment by wikijm** [comment]
OK super 😃
