### ISSUE TITLE
erreur pour afficher TMC

### ISSUE THREAD

**Issue by druzy** [wikijm/jarvis-freeboxplayer#12]
Une erreur dans le fichier command ne permet pas à la freebox d'afficher TMC.
La commande 
`*AFFICH*TMC|*MET*LA*10*==say "T M C" && jv_curl "${freeboxplayer_url}10">/dev/null`
doit être remplacée par 
`*AFFICH*TMC|*MET*LA*10*==say "T M C" && jv_curl "${freeboxplayer_url}1 && jv_curl "${freeboxplayer_url}0">/dev/null`

**Comment by wikijm** [comment]
Bonsoir @druzy 

Merci pour le signalement et la proposition de solution 😃 
Je viens d'apporter la correction grâce au commit https://github.com/wikijm/jarvis-freeboxplayer/commit/dcde041de14de0a4952a887c976be8320983b287.

Bonne soirée,
WikiJM
