### ISSUE TITLE
erreur avec plugin Freebox 

### ISSUE THREAD

**Issue by Chris54220** [wikijm/jarvis-freeboxplayer#2]
Bonjour j'ai un petit soucis avec le plugin de la Freebox

alors j'ai 2 lecteur donc j'ai changer le fichier commande pour que les commande fonctionne sur hd2 au lieu de hd1

mais sa me renvois cela 

Forbidden
 You don't have permission to access this file on this server.
 Cheyenne/2.2.8 Server at localhost Port 80

**Comment by wikijm** [comment]
Bonjour, 

J'ai un doute quant au bon fonctionnement de la variable contenant le code de télécommande. 

Si tu remplace cette variable directement par le code, est ce que cela fonctionne ?

**Comment by Chris54220** [comment]
bon bas je te confirme que la variable ne fonctionne pas car avec le code direct il a pas de soucis

**Comment by wikijm** [comment]
J'ai fais les commit suivants :
- [f0503cd2a4e018bb445a30fe5e8bc8924a47c26d](https://github.com/wikijm/jarvis-freeboxplayer/commit/f0503cd2a4e018bb445a30fe5e8bc8924a47c26d)
- [cc55eab28479fb8a27e9eb96fdb810f6ebdd6df3](https://github.com/wikijm/jarvis-freeboxplayer/commit/cc55eab28479fb8a27e9eb96fdb810f6ebdd6df3#diff-cf60ee1ee76f499cba0d4528bdca10b9)

Est ce que cela fonctionne mieux @Chris54220 ? Je me suis basé sur le module [LiveboxTV](http://domotiquefacile.fr/jarvis/plugins/liveboxtv).

**Comment by wikijm** [comment]
@Chris54220 J'ai fais le commit https://github.com/wikijm/jarvis-freeboxplayer/commit/cd2144508d927a78651c61f70aacd98c0d3463fc, est ce que tu pourrais retester ?
