### ISSUE TITLE
Bonjour Wikijm... un petit bug à l'install...

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [wikijm/jarvis-freeboxplayer#3]
Bonjour lors de l'installation du plugin il dit: 

fatal: le dépôt 'null.git' n'existe pas
ERROR: An error has occured

J'ai forcé l'installation en allant directement le chercher sur ce GIT.

**Comment by wikijm** [comment]
Bonjour @Jean-Bernard-Hallez 

Le problème d'installation se pose lorsque tu tente de l'installer :
- A partir du site domotiquefacile.com ?
- Directement dans le store de Jarvis ?

**Comment by Jean-Bernard-Hallez** [comment]
désolé pour le décalage horaire c' est lorsque je clique sur le store de JarvisEntre-temps je vois ça fais une modification je te dirai si ça fonctionne et de mon côté je recommencerai à zéro...

Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : PGP 2F93D5AF <notifications@github.com> 
Date : 13/12/2016  16:31  (GMT+01:00) 
À : wikijm/jarvis-freeboxplayer <jarvis-freeboxplayer@noreply.github.com> 
Cc : Hallez <jbhallez@aol.com>, Mention <mention@noreply.github.com> 
Objet : Re: [wikijm/jarvis-freeboxplayer] Bonjour Wikijm... un petit bug à l'install... (#3) 

Bonjour @Jean-Bernard-Hallez
Le problème d'installation se pose lorsque tu tente de l'installer :

A partir du site domotiquefacile.com ?
Directement dans le store de Jarvis ?


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wikijm/jarvis-freeboxplayer","title":"wikijm/jarvis-freeboxplayer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/wikijm/jarvis-freeboxplayer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wikijm in #3: Bonjour @Jean-Bernard-Hallez \r\n\r\nLe problème d'installation se pose lorsque tu tente de l'installer :\r\n- A partir du site domotiquefacile.com ?\r\n- Directement dans le store de Jarvis ?"}],"action":{"name":"View Issue","url":"https://github.com/wikijm/jarvis-freeboxplayer/issues/3#issuecomment-266769259"}}}

**Comment by wikijm** [comment]
Bonjour @Jean-Bernard-Hallez, as-tu eu le temps de retester ?

**Comment by Jean-Bernard-Hallez** [comment]
Bonjour... A l'instant, je l'ai supprimé pour essayer de le réinstaller et j'ai 
fatal: le dépôt 'null.git' n'existe pas
Non résolu...

**Comment by Andes2k** [comment]
Bonjour à vous 2,

en effet le problème est identique pour moi lorsque je tente d'installer depuis le Jarvis directement. 
L'install fonctionne par contre correctement avec la commande : 
`./jarvis.sh -p https://github.com/wikijm/jarvis-freeboxplayer`

;)

**Comment by wikijm** [comment]
Bonjour messieurs, 

J’arrive aussi à reproduire votre problème (KO par Jarvis, OK par la commande `./jarvis.sh -p XXXXX`).
Je vais essayer de voir avec @alexylem

**Comment by alexylem** [comment]
Je confirme:
![image](https://cloud.githubusercontent.com/assets/11017174/21581279/75c2ca3c-d02b-11e6-8614-2420998c5c7a.png)

Je regarde...

**Comment by alexylem** [comment]
J'ai trouvé, un espace s'est glissé à la fin du titre du plugin sur le webstore... je corrige

**Comment by alexylem** [comment]
Corrigé, ca devrait fonctionner maintenant. Bonne année à vous 😄

**Comment by wikijm** [comment]
Merci @alexylem :-)
Bonne année à toi aussi ;-)
