### ISSUE TITLE
commande non reconnu ?

### ISSUE THREAD

**Issue by koua29** [wikijm/jarvis-freeboxplayer#4]
Bonjour,

quand j'exécute la commande à la main => wget -qO /dev/null "http://hd1.freebox.fr/pub/remote_control?code=*******&key=power"  ça fonctionne bien , ma freebox s'allume.

Par contre via jarvis, il me répond commande non reconnu
arnaud: allume la tele
jarvis: La télé va s'allumer
jarvis: **Commande non reconnu**
arnaud:

en mode debug 
arnaud: (listening...)
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.2 1% trim 0 10
DEBUG: speech duration was 15 (10 = 1 sec)
DEBUG: token missing or expired
DEBUG: json=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6Imh0dHBzOi8vc3BlZWNoLnBsYXRmb3JtLmJpbmcuY29tIiwic3Vic2NyaXB0aW9uLWlkIjoiYjMzMjRkNzZiYzgxNDU1MDgzYjcyMzYxN2U4OGE0YjMiLCJwcm9kdWN0LWlkIjoiQmluZy5TcGVlY2guUHJldmlldyIsImNvZ25pdGl2ZS1zZXJ2aWNlcy1lbmRwb2ludCI6Imh0dHBzOi8vYXBpLmNvZ25pdGl2ZS5taWNyb3NvZnQuY29tL2ludGVybmFsL3YxLjAvIiwiYXp1cmUtcmVzb3VyY2UtaWQiOiIiLCJpc3MiOiJ1cm46bXMuY29nbml0aXZlc2VydmljZXMiLCJhdWQiOiJ1cm46bXMuc3BlZWNoIiwiZXhwIjoxNDgyOTM5ODU3fQ.bOZmwfXi3PLlxPLp67kzReSIIs6xAb7-e1egujHiIOo
DEBUG: token will expire in 590 seconds
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=0e965132-1e4f-46d9-92bc-c620f0483d48&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"allume la télé","lexical":"allume la télé","properties":{"requestid":"44f7532d-dea3-4a17-87fe-f1b614041ff7","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"allume la télé","lexical":"allume la télé","confidence":"0.9525475","properties":{"HIGHCONF":"1"}}]}
allume la télé
$> say "La télé va s'allumer" && wget -qO /dev/null "${freeboxplayer_url}power" && sleep 12 && wget -qO /dev/null "${freeboxplayer_url}home" && wget -qO /dev/null "${freeboxplayer_url}ok"
jarvis: La télé va s'allumer
--2016-12-28 16:34:17--  http://www.voxygen.fr/sites/all/modules/voxygen_voices/assets/proxy/index.php?method=redirect&text=La%20t%C3%A9l%C3%A9%20va%20s'allumer&voice=Loic&ts=1480362849466
Resolving www.voxygen.fr (www.voxygen.fr)... 37.59.11.12
Connecting to www.voxygen.fr (www.voxygen.fr)|37.59.11.12|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.voxygen.fr/sites/all/modules/voxygen_voices/assets/proxy/index.php?method=redirect&text=La%20t%C3%A9l%C3%A9%20va%20s'allumer&voice=Loic&ts=1480362849466 [following]
--2016-12-28 16:34:17--  https://www.voxygen.fr/sites/all/modules/voxygen_voices/assets/proxy/index.php?method=redirect&text=La%20t%C3%A9l%C3%A9%20va%20s'allumer&voice=Loic&ts=1480362849466
Connecting to www.voxygen.fr (www.voxygen.fr)|37.59.11.12|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: //demows.voxygen.fr/ws/tts1?text=La+t%C3%A9l%C3%A9+va+s%27allumer&voice=Loic&header=headerless&coding=mp3%3A128-0&user=anders.ellersgaard%40mindlab.dk&hmac=fcd1457ce54596240a1b8a00fa18ec0b [following]
--2016-12-28 16:34:17--  https://demows.voxygen.fr/ws/tts1?text=La+t%C3%A9l%C3%A9+va+s%27allumer&voice=Loic&header=headerless&coding=mp3%3A128-0&user=anders.ellersgaard%40mindlab.dk&hmac=fcd1457ce54596240a1b8a00fa18ec0b
Resolving demows.voxygen.fr (demows.voxygen.fr)... 5.135.187.57
Connecting to demows.voxygen.fr (demows.voxygen.fr)|5.135.187.57|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19008 (19K) [audio/mpeg]
Saving to: ‘/tmp/la_tele_va_sallumer.mp3’

/tmp/la_tele_va_sallume 100%[==============================>]  18.56K  --.-KB/s   in 0.001s

2016-12-28 16:34:17 (28.0 MB/s) - ‘/tmp/la_tele_va_sallumer.mp3’ saved [19008/19008]

jarvis: Commande non reconnu
--2016-12-28 16:34:19--  http://www.voxygen.fr/sites/all/modules/voxygen_voices/assets/proxy/index.php?method=redirect&text=Commande%20non%20reconnu&voice=Loic&ts=1480362849466
Resolving www.voxygen.fr (www.voxygen.fr)... 37.59.11.12
Connecting to www.voxygen.fr (www.voxygen.fr)|37.59.11.12|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.voxygen.fr/sites/all/modules/voxygen_voices/assets/proxy/index.php?method=redirect&text=Commande%20non%20reconnu&voice=Loic&ts=1480362849466 [following]
--2016-12-28 16:34:19--  https://www.voxygen.fr/sites/all/modules/voxygen_voices/assets/proxy/index.php?method=redirect&text=Commande%20non%20reconnu&voice=Loic&ts=1480362849466
Connecting to www.voxygen.fr (www.voxygen.fr)|37.59.11.12|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: //demows.voxygen.fr/ws/tts1?text=Commande+non+reconnu&voice=Loic&header=headerless&coding=mp3%3A128-0&user=anders.ellersgaard%40mindlab.dk&hmac=0d59b120ce1e9ab20b81bc2f6d9a86b7 [following]
--2016-12-28 16:34:19--  https://demows.voxygen.fr/ws/tts1?text=Commande+non+reconnu&voice=Loic&header=headerless&coding=mp3%3A128-0&user=anders.ellersgaard%40mindlab.dk&hmac=0d59b120ce1e9ab20b81bc2f6d9a86b7
Resolving demows.voxygen.fr (demows.voxygen.fr)... 5.135.187.57
Connecting to demows.voxygen.fr (demows.voxygen.fr)|5.135.187.57|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16704 (16K) [audio/mpeg]
Saving to: ‘/tmp/commande_non_reconnu.mp3’

/tmp/commande_non_recon 100%[==============================>]  16.31K  --.-KB/s   in 0.001s

2016-12-28 16:34:20 (31.7 MB/s) - ‘/tmp/commande_non_reconnu.mp3’ saved [16704/16704]

arnaud: (listening...)
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.2 1% trim 0 10

une idée ?
Pour l'installation, j'ai du la faire via le repository git car il y avait une erreur via l'interface jarvis.
Mais il y a déjà un ticket sur le sujet.

**Comment by koua29** [comment]
si je met HD1 et mon code freebox en dure dans le fichier function.sh , ça fonctionne bien.
En fait le problème semble venir de l'intégration des variables du config.sh dans le fichier function.sh.

**Comment by wikijm** [comment]
@koua29 Je confirme ton diagnostic,  je vais en parler avec @alexylem

**Comment by alexylem** [comment]
Je regarde...

**Comment by alexylem** [comment]
Je me suis bien arraché les cheveux la-dessus...
Le pb semble venir de l'encodage de ton fichier `config.sh` DOS au lieu de UNIX pour les retour chariots:
```shell
$> cat config.sh 
freeboxplayer_remotecode="12345678"
freeboxplayer_hdn="hd1"
freeboxplayer_url="http://$freeboxplayer_hdn.freebox.fr/pub/remote_control?code=$freeboxplayer_remotecode&key="
echo $freeboxplayer_url
$> source config.sh
&key=box.fr/pub/remote_control?code=12345678
```
Ici comme tu vois, le echo afficher n'importe quoi, la substitution des variables n'est pas bien faite.

En convertissant le fichier en UNIX:
```shell
$> sed 's/^M$//' config.sh > config2.sh
$> source config2.sh
http://hd1.freebox.fr/pub/remote_control?code=12345678&key=
```
Là c'est bon. Donc rien à voir avec Jarvis 😄 
Ne copie pas la commande telle qu'elle pour faire la conversion, il faut faire une combinaison pour obtenir le caractère `^M` en faisant `Ctrl+V` puis `Ctrl+M` dans le terminal.

Voilà il te reste à `corriger` ton fichier `config.sh` (et probablement les autres aussi), voir changer les préférences de ton éditeur de texte (ou développer directement sur le raspberry pi 👍 ).

**Comment by wikijm** [comment]
Un grand merci @alexylem (j'espère qu'il te restera des cheveux pour 2017 😄).
J'essaie de modifier tout ça ce soir.

**Comment by wikijm** [comment]
@koua29 Tu peux mettre à jour le plugin et réessayer ?

**Comment by koua29** [comment]
je m'en occupe demain, déjà merci !
