### ISSUE TITLE
améliorer les commandes

### ISSUE THREAD

**Issue by koua29** [wikijm/jarvis-freeboxplayer#5]
Pour que ça fonctionne bien , il faudrait améliorer les commandes  en mettant plusieurs choix.

arnaud: affiche m six
jarvis: Je ne comprends pas?: affiche m six

arnaud: ?affiche TF un
jarvis: Je ne comprends pas?: affiche TF un

**Comment by wikijm** [comment]
Tu penses à mettre "thé F un" | "TF un"  | "T F 1" pour TF1 par exemple ?

**Comment by wikijm** [comment]
https://github.com/wikijm/jarvis-freeboxplayer/commit/22cbf6cac77ad74fda03e79df7e41d8fdf0d04b6 effectué pour répondre à ta demande @koua29. Merci pour la proposition ;-)
