### ISSUE TITLE
Partage de mes commandes Freeboxtv pour google now via android

### ISSUE THREAD

**Issue by tchoul** [wikijm/jarvis-freeboxplayer#6]
@wikijm si ça t'interesse pour freeboxtv freebox v6

`*ZAP*SEUL*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=1" && sleep 4  && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=5" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=9" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=0"`

`*CHANG*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_inc"`

`*REVIEN*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prgm_dec"`

`*ALLUM*LA*TELE*==say "La télé va s'allumer" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=power" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=home" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=ok"`

`*RETOUR*TELE|*REVIEN*TELE==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=home" && sleep 3 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=home" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=ok"`

`*ETEINS*LA*TELE*|*STOP LA TELE*==say "La télé va s'éteindre" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=power">/dev/null`

`*BAISSE UN PEU LE VOLUME*|*BAISSE UN PEU LE SON*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec"`

`*BAISSE LE VOLUME*|*BAISSE LE SON*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec"`

`*BAISSE*BEAUCOUP*LE*VOLUME*|*BAISSE*BEAUCOUP*LE SON*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_dec"`

`*AUGMENTE UN PEU LE VOLUME*|AUGMENTE UN PEU LE SON*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc"`

`*AUGMENTE LE VOLUME*|*AUGMENTE LE SON*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc"`

`*AUGMENTE*BEAUCOUP*LE VOLUME*|*AUGMENTE*BEAUCOUP*LE SON*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=vol_inc"`

`*ALLUME LE SON*|*ALLUME LE VOUME*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=mute">/dev/null`

`*COUPE LE SON*|*COUPE LE VOLUME*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=mute">/dev/null`

`*ENREGISTRE==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=rec">/dev/null`

`*PLAY|*PAUSE|*POSE|*LECTURE==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=play">/dev/null`

`*REMONTE*TROIS*|*REMONTE*3*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=up" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=up" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=up"`

`*REMONTE*QUATRE*|*REMONTE*4*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=up" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=up" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=up" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=up"`

`*REMONTE*CINQ*|*REMONTE*5*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=up" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=up" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=up" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=up" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=up"`

`*REMONTE*DE*|*REMONTE*2*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=up" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=up" `

`*REMONTE*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=up"`

`*DESCEN*TROIS*|*DESCEN*3*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down"`

`*DESCEN*QUATRE*|*DESCEN*4*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down"`

`*DESCEN*5*|*D105*|*DES 105*|*205*X*|*205*FOIS*|*D205*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down"`

`*DESCEN*DE*|*DESCEN*2*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down"`

`*DESCENDS|*DESCEND==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down"`

`*GAUCHE*DE*|*GAUCHE*2*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=left" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=left"`

`*GAUCHE*TROIS*|*GAUCHE*3*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=left" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=left" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=left"`

`*GAUCHE*QUATRE*|*GAUCHE*4*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=left" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=left" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=left" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=left"`

`*GAUCHE*CINQ*|*GAUCHE*5*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=left" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=left" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=left" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=left" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=left"`

`*GAUCHE*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=left">/dev/null`

`*DROITE*DE*|*DROITE*2*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right"`

`*DROITE*TROIS*|*DROITE*3*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right"`

`*DROITE*QUATRE*|*DROITE*4*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right"`

`*DROITE*CINQ*|*DROITE*5*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right"`

`*DROITE*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right"`

`*OK*|*HOCKEY*|OKAY*==say "OK" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=ok"`

`*CHAPITRE*PRECEDENT*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=prev"`

`*CHAPITRE*SUIVANT*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=next"`

`*AVANCE*TRES*RAPIDE*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=fwd" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=fwd" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=fwd" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=fwd" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=fwd" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=fwd" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=fwd"`

`*AVANCE*RAPIDE*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=fwd" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=fwd" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=fwd"`

`*RETOUR*EN*ARRIERE*TRES*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=bwd" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=bwd" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=bwd" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=bwd" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=bwd" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=fwd" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=fwd"`

`*RETOUR*EN*ARRIERE==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=bwd" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=bwd"jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=bwd"`

`*RETOUR*==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=red"`

`*MENU==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=green"`

`*INFO==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=yellow"`

`*RECHERCHE==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=blue"`

`*ACCUEIL==say "Retour à l'accueil" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=home" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=home"`

`*TELECHARGEMENT|*TELECHARGEMENTS==jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=home" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=home" && sleep 3  && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=right" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=ok" && sleep 4 &&  jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=ok" && sleep 1 && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=down" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=ok"`

`*AFFICH*MOZAIQUE==say "Mozaïque" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=0"`

`*AFFICH*TF1*|*MET*LA*UN*==say "TF1" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=1">/dev/null`

`*AFFICH*FRANCE 2*|*MET*LA*2*==say "France 2" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=2">/dev/null`

`*AFFICH*FRANCE 3*|*MET*LA*3*==say "France 3" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=3">/dev/null`

`*AFFICH*FRANCE 4*|*MET*LA*14*==say "France 4" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=1" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=4"`

`*AFFICH*CANAL==say "Canal plus" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=4"`

`*AFFICH*FRANCE 5*|*MET*LA*5*==say "France 5" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=5">/dev/null`

`*AFFICH*M6*|*MET*LA*6*==say "M 6" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=6">/dev/null`

`*AFFICH*ARTE|*MET*LA*SEPT*==say "ARTER" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=7">/dev/null`

`*AFFICH*C8*|*MET*LA*8*==say "C 8" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=8">/dev/null`
`
*AFFICH*W9*|*MET*LA*9*==say "W 9" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=9">/dev/null`

`*AFFICH*TMC|*MET*LA*10*==say "T M C" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=10">/dev/null`

`*AFFICH*NT1|*AFFICH*NT*A|*MET*LA*11*==say "N T 1" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=1" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=1">/dev/null`

`*AFFICH*NRJ12*|*AFFICH*NRJ*DOUZ*==say "N R J 12" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=1" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=2">/dev/null`

`*AFFICH*LCP*==say "LCP" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=1" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=3">/dev/null`

`*AFFICH*BFM==say "B F M" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=1" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=5">/dev/null`

`*AFFICH*ITELE==say "I Télé" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=1" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=6">/dev/null`

`*AFFICH*CSTAR==say "C STAR" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=1" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=7">/dev/null`

`*AFFICH*GULLI*==say "GULLI" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=1" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=8">/dev/null`

`*AFFICH*FRANC*O*|AFFICH*FRANCE*O*==say "FRANCE O" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=1" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=9">/dev/null`

`*AFFICH*HD1*|AFFICH*HD 1*==say "H D 1" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=2" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=0">/dev/null`

`*AFFICH*EQUIPE*==say "L'équipe" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=2" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=1">/dev/null`

`*AFFICH*SIX*TER*|*AFFICH*SISTER*==say "6 TER" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=2" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=2">/dev/null`

`*AFFICH*NUMERO*23*==say "NUMERO 23" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=2" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=3">/dev/null`

`*AFFICH*RMC*DECOUVERT*==say "RMC DECOUVERTE" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=2" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=4">/dev/null`

`*AFFICH*CHERI*25*|*AFFICH*CHERI*VINGT*CINQ*==say "CHERIE 25" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=2" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=5">/dev/null`
`
*AFFICH*LCI*==say "LCI" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=2" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=6">/dev/null`

`*AFFICH*FRANCE INFO==say "France info" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=2" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=7"`

`*AFFICH*PARIS PREMIER*==say "Paris première" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=2" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=8"`

`*AFFICH*RTL9*==say "RTL9" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=2" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=9">/dev/null`

`*AFFICH*GAME*==say "GAME ONE" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=3" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=7">/dev/null`

`*AFFICH*TEVA==say "TEVA" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=3" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=8"`

`*AFFICH*AB1==say "AB1" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=3" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=9"`

`*AFFICH*COMEDIE*==say "COMEDIE+" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=8" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=0">/dev/null`

`*AFFICH*PLANE*==say "PLANETE+" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=5" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=9">/dev/null`

`*AFFICH*FIF*|*AFFICH*SISS*|AFFICH*SYFY==say "Syfy" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=8" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=2">/dev/null`

`*AFFICH*MANGA*==say "MANGAS" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=9" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=0">/dev/null`

`*AFFICH*NO LIFE==say "No lfe" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=9" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=3"`

`*AFFICH*TOONAMI==say "Tounami" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=1" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=5" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=4"`

`*AFFICH*LUCKY JACK==say "Lucky jack" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=2" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=4" && jv_curl "http://hd1.freebox.fr/pub/remote_control?code=57775659&key=4"`

**Comment by wikijm** [comment]
J'ai amélioré le fichier de commandes grâce à quelques unes de tes suggestions (voir https://github.com/wikijm/jarvis-freeboxplayer/commit/777a91b1c8ae3f4b120ad150d94e0436992af163).

Merci pour ton travail @Tchoul :-)
