### ISSUE TITLE
Volume + et -

### ISSUE THREAD

**Issue by prosper4tie** [wikijm/jarvis-freeboxplayer#7]
Salut,

Juste une petite info, la commande volume + et - ne fonctionne pas chez moi.
Je suis obligé de changer la commande vol_decr en vol_dec et vol_incr en vol_inc.

Voici également une ligne pour monter ou descendre de manière significative le son
MONTE LE SON==for i in `seq 1 10`; do jv_curl "${freeboxplayer_url}vol_inc"; done

A+

**Comment by wikijm** [comment]
Bonjour @prosper4tie,

En effet, erreur de ma part dans la touche appelée :-/

Peux-tu me décrire ce que fais la commande que tu propose ?
Elle augmente de 10 niveaux le son ?

**Comment by prosper4tie** [comment]
Tout à fait, pour mon utilisation, je trouvais pas pertinent de monter le son de 1 point seulement :)

**Comment by wikijm** [comment]
Je viens de faire un commit pour intégrer ton astuce, et rajouter `*MON*SON*` au fichier de commande.
Si tu en as d'autres dans le même style, je suis preneur ;-)
