### ISSUE TITLE
TF1 est interprété en TF UN

### ISSUE THREAD

**Issue by torrwarez** [wikijm/jarvis-freeboxplayer#9]
Bonjour,

Comment associer la commande AFFICHE TF UN à Affiche TF1 ?

Car quand on prononce Affiche TF1 jarvis l'interprète en Affiche TF UN et du coup le plugin ne comprends pas.

Merci,
Steeve

**Comment by wikijm** [comment]
Bonsoir @torrwarez 

Toutes les commandes sont dans le fichier [jarvis-freeboxplayer/fr/commands](https://github.com/wikijm/jarvis-freeboxplayer/fr/commands).
Dans ton cas il faut regarder la ligne suivante : https://github.com/wikijm/jarvis-freeboxplayer/blob/fa05207162591ea62a86cd4c4dfafd51a765af58/fr/commands#L30

Le commit https://github.com/wikijm/jarvis-freeboxplayer/commit/fa05207162591ea62a86cd4c4dfafd51a765af58 a fait passé cette ligne de `*AFFICH*TF1*|*MET*LA*UN*==say "TF1" && jv_curl "${freeboxplayer_url}1">/dev/null` à `*AFFICH*TF1|*AFFICH*TF*UN|*MET*LA*UN*==say "TF1" && jv_curl "${freeboxplayer_url}1">/dev/null`, ce qui devrait répondre à ton besoin.


Merci de me faire un retour 😃

**Comment by torrwarez** [comment]
Salut ! Merci pour le retour rapide.

Justement j'ai fais la même modif car j'ai finalement trouvé le fichier par la suite.

Du coup j'ai fais la même chose pour toutes les autres chaînes. Je sais pas si je dois poster mon fichier ici ?

J'ai vu également qu'une mise à jour était dispo, elle prends en compte la modif que pour TF1 ou pour toutes les autres chaînes ? Car sinon je préfère garder mon fichier.

Merci :)

**Comment by wikijm** [comment]
Tu semble utiliser GitHub depuis peu.
Je t'invite à :
A) Regarder comment faire pour faire un fork de ce repository (bouton fork en haut de page, afin d'en faire une copie sur ton compte), faire un commit dessus (y apporter une modification et la publier sur ton repository) puis d'envoyer une pull request (proposer au créateur initial du code une copie).

B) Me copier-coller ici les modifications que tu y a a apporté.

Le choix A) te fait monter en compétence et permettra de voir que c'est toi qui a apporté une amélioration au plugin. Le choix B) est plus simple mais à mon sens moins gratifiant.

Enfin, la mise à jour correspond à ma modification. Si tu choisis A), la prochaine intégrera ce que tu apporte comme amélioration 😄
